version: '1.0'
name: pipeline-20230418
displayName: pipeline-20230418
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
stages:
  - name: stage-1f47aad9
    displayName: checkoutmain
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 12.16.1
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install -g gitbook-cli
          - gitbook install
          - npm install -g gitbook-summary
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
